export {
  DEFAULT_DETAIL_INTERVAL,
  DEFAULT_DETAIL_CANDLE_LIMIT,
  DETAIL_HISTORY_PAGE_SIZE,
  DETAIL_HISTORY_EDGE_BARS,
  DETAIL_MAX_CANDLES,
  DEFAULT_RSI_PERIOD,
  DEFAULT_EMA_PERIODS,
  DETAIL_TICKER_POLL_MS,
  DETAIL_SERIES_POLL_MS,
} from '@/config/detailConstants';
